apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../..

images:
  - name: universal-api-gateway
    newName: ghcr.io/poisonoakey/universal-api-gateway
    newTag: 073808e826614400418ee027aacb1f7121c7434f

patches:
  - target:
      kind: Service
      name: universal-api-gateway
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
      - op: remove
        path: /spec/ports/0/nodePort
